# Change these first
owner: ubitechq # Your GitHub username
repo: docker-ubitec-io-status-page # Your GitHub repository name

# Add your sites here
sites:
  - name: docker.ubitec.io Singapore
    url: https://docker-ap-southeast-1.ubitec.io/health
    headers:
      - "Authorization: Bearer $DOCKER_UBITEC_IO_HEALTHCHECK_USER"
  - name: docker.ubitec.io Frankfurt
    url: https://docker-eu-central-1.ubitec.io/health
    headers:
      - "Authorization: Bearer $DOCKER_UBITEC_IO_HEALTHCHECK_USER"

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: status.docker.ubitec.io
  # Uncomment the following line if you don't have a custom domain and add your repo name
  # baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: ubitec's Docker Registry Status Page
  introTitle: "ubitec's Docker Registry Is Serving Docker Images for ubitec's Customers Worldwide"
  introMessage: 
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/ubitechq/docker-ubitec-io-status-page

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
